CREATE DATABASE HR_PROJECT;
USE HR_PROJECT;

SELECT* FROM hr;
ALTER TABLE hr
CHANGE COLUMN ï»¿id EMP_ID VARCHAR(20) NULL;

DESCRIBE hr;
SELECT birthdate FROM hr;

SET sql_safe_updates = 0;
UPDATE hr
SET birthdate = CASE
WHEN birthdate LIKE'%/%' THEN DATE_FORMAT(STR_TO_DATE(birthdate, '%m/%d/%Y'), '%Y-%m-%d') 
WHEN birthdate LIKE'%-%' THEN DATE_FORMAT(STR_TO_DATE(birthdate, '%m-%d-%Y'), '%Y-%m-%d') 
ELSE NULL
END;
ALTER TABLE hr
MODIFY COLUMN birthdate DATE;
SELECT birthdate FROM hr;

UPDATE hr
SET hire_date = CASE
WHEN hire_date LIKE'%/%' THEN DATE_FORMAT(STR_TO_DATE(hire_date, '%m/%d/%Y'), '%Y-%m-%d') 
WHEN hire_date LIKE'%-%' THEN DATE_FORMAT(STR_TO_DATE(hire_date, '%m-%d-%Y'), '%Y-%m-%d') 
ELSE NULL
END;
ALTER TABLE hr
MODIFY COLUMN hire_date DATE;
SELECT hire_date FROM hr;


SELECT termdate FROM hr;

UPDATE hr
SET termdate = IF(termdate IS NOT NULL AND termdate != '', date(str_to_date(termdate, '%Y-%m-%d %H:%i:%s UTC')), '0000-00-00')
WHERE true;

SELECT termdate FROM hr;

SET sql_mode = 'ALLOW_INVALID_DATES';

ALTER TABLE hr
MODIFY COLUMN termdate DATE;

ALTER TABLE hr ADD COLUMN AGE INT;

UPDATE hr
SET AGE= TIMESTAMPDIFF(YEAR,birthdate,CURDATE());

SELECT birthdate,AGE FROM hr;

SELECT 
min(AGE) AS youngest,
max(AGE) AS oldest
FROM hr;

SELECT COUNT(*) FROM hr WHERE AGE<18;
DELETE FROM hr WHERE AGE<=18;


-- QUESTIONS TO BE ANSWERED FROM THE GIVEN DATASET:
-- 1) WHAT IS THE GENDER BREAKDOWN OF EMPLOYEES IN THE COMPANY ?
SELECT GENDER,COUNT(*) AS COUNT
FROM hr
WHERE termdate= '0000-00-00'
GROUP BY GENDER;
-- 2) WHAT IS THE RACE/ETHNICITY BREAKDOWN OF EMPLOYEES IN THE COMPANY?
SELECT RACE, COUNT(*) AS COUNT
FROM hr
WHERE TERMDATE='0000-00-00'
GROUP BY RACE
ORDER BY COUNT(*) DESC;

-- 3) WHAT IS THE AGE DISTRIBUTION OF EMPLOYEES IN THE COMPANY?
SELECT
MIN(AGE) AS YOUNGEST,
MAX(AGE) AS OLDEST
FROM hr
WHERE TERMDATE='0000-00-00';

SELECT
CASE
WHEN AGE>= 18 AND AGE<= 24 THEN'18-24'
WHEN AGE>= 25 AND AGE<= 34 THEN'25-34'
WHEN AGE>= 35 AND AGE<= 44 THEN'35-44'
WHEN AGE>= 45 AND AGE<= 54 THEN'45-54'
WHEN AGE>= 55 AND AGE<= 64 THEN'55-64'
ELSE '65+'
END AS AGE_GROUP,
COUNT(*) AS COUNT
FROM hr
WHERE TERMDATE='0000-00-00'
GROUP BY AGE_GROUP
ORDER BY AGE_GROUP ;

SELECT
CASE
WHEN AGE>= 18 AND AGE<= 24 THEN'18-24'
WHEN AGE>= 25 AND AGE<= 34 THEN'25-34'
WHEN AGE>= 35 AND AGE<= 44 THEN'35-44'
WHEN AGE>= 45 AND AGE<= 54 THEN'45-54'
WHEN AGE>= 55 AND AGE<= 64 THEN'55-64'
ELSE '65+'
END AS AGE_GROUP, GENDER,
COUNT(*) AS COUNT
FROM hr
WHERE TERMDATE='0000-00-00'
GROUP BY AGE_GROUP, GENDER
ORDER BY AGE_GROUP, GENDER ;
   
   
-- QUESTION 4) HOW MANY EMPLOYEES WORK IN HEADQUARTERS VERSUS REMOTE LOCATION?
SELECT LOCATION, COUNT(*) AS COUNT
FROM hr
WHERE TERMDATE='0000-00-00'
GROUP BY LOCATION;

-- QUESTION 5) WHAT IS THE AVERAGE LENGTH OF EMPLOYMENT FOR EMPLOYEES WHO HAVE BEEN TERMINATED?
SELECT 
ROUND(AVG(DATEDIFF(termdate, hire_date))/365,0) AS AVG_LENGTH_EMPLOYMENT
FROM hr
WHERE termdate<= curdate() AND TERMDATE<>'0000-00-00';

-- QUESTION 6: HOW DOES THE GENDER DISTRIBUTION VARY ACROSS DEPARTMENTS AND JOB TITLES?

SELECT DEPARTMENT,GENDER, COUNT(*) AS COUNT
FROM hr
WHERE TERMDATE='0000-00-00'
GROUP BY DEPARTMENT,GENDER
ORDER BY DEPARTMENT;

-- QUESTION 7) WHAT IS THE DISTRIBUTION OF JOB TITLES ACROSS THE COMPANY?

SELECT JOBTITLE, COUNT(*) AS COUNT
FROM hr
WHERE TERMDATE='0000-00-00'
GROUP BY JOBTITLE
ORDER BY JOBTITLE DESC;

-- QUESTION 8) WHICH DEPARTMENT HAS THE HIGHEST ATTRITION RATE?
SELECT department, total_count, terminated_count,
terminated_count/total_count AS termination_rate
FROM (
       SELECT department,
       count(*) AS total_count,
       sum(CASE WHEN TERMDATE<> '0000-00-00' AND TERMDATE<= CURDATE() THEN 1 ELSE 0 END) AS TERMINATED_COUNT
       FROM hr
       WHERE AGE>= 18
       GROUP BY DEPARTMENT
       ) AS subquery
ORDER BY TERMINATION_RATE DESC;

-- 9) WHAT IS THE DISTRIBUTION OF EMPLOYEES ACROSS LOCATIONS BY CITY AND STATE?
SELECT LOCATION_STATE, COUNT(*) AS COUNT
FROM hr
WHERE TERMDATE='0000-00-00'
GROUP BY LOCATION_STATE
ORDER BY COUNT DESC;

-- 10) HOW HAS THE COMPANY'S EMPLOYEE COUNT CHANGED OVER TIME BASED ON HIRE AND TERM DATES?
ALTER TABLE hr
ADD COLUMN TERMINATIONS INT;
ALTER TABLE hr
DROP TERMINATIONS;
SELECT
YEAR,
HIRES,
TERMINATIONS,
HIRES-TERMINATIONS AS NET_CHANGE,
ROUND((HIRES-TERMINATIONS)/HIRES*100,2) AS NET_CHANGE_PERCENT
FROM(
      SELECT 
      YEAR (HIRE_DATE) AS YEAR,
      COUNT(*) AS HIRES,
      SUM(CASE WHEN termdate<>'0000-00-00' AND termdate <=CURDATE() THEN 1 ELSE 0 END) AS TERMINATIONS
      FROM hr
      WHERE AGE>=18
      GROUP BY YEAR (HIRE_DATE)
      ) AS subquery
      ORDER BY YEAR ASC;
-- 10) WHAT IS THE TENURE DISTRIBUTION FOR EACH DEPARTMENT?

SELECT DEPARTMENT, ROUND(AVG(DATEDIFF(TERMDATE,HIRE_DATE)/365),0) AS AVG_TENURE
FROM hr
WHERE TERMDATE<= CURDATE() AND TERMDATE<> '0000-00-00' AND AGE>=18
GROUP BY DEPARTMENT;

-- END OF QUERYING
     





